### ISSUE TITLE
app.runのhostを0.0.0.0にする

### ISSUE THREAD

**Issue by potato4d** [tonkatsu-ansin/ThunderWeapon#2]
外部アクセス周りのため

**Comment by himanoa** [comment]
外部アクセスしたいなら
`make production-run`で鯖起動するといいかも

**Comment by himanoa** [comment]
あと基本的にnginxとかでリバースプロキシ噛ませるほうがいいし、アプリケーション鯖をそのまま外部に露出するのは避けたい方針がある

**Comment by potato4d** [comment]
Productionならそれで良いんだけど、ローカルのPython環境がアレだから外出して繋いで触っててつらくなったみたいなアレがあった

**Comment by himanoa** [comment]
むむ？いまいちなにがしたいのかよくわからん

**Comment by potato4d** [comment]
Pythonのコードそんなに触らんからc9にぶん投げていたという話がある（環境入れるわ）

**Comment by himanoa** [comment]
やった
